import io
import os
import pandas as pd
import re

def fasta_to_all_chars_dataframe(filepath):
    """ 
    Parses a FASTA file and returns a DataFrame with all characters enumerated
    """
    with open(filepath, 'r') as file:
        position = 1  
        data = []  
        for line in file:
            for char in line:
                if char == '\n':
                    data.append((position, 'line_break', '\\n'))
                else:
                    data.append((position, 'sequence' if char != '>' else 'header', char))
                position += 1

    reference_df = pd.DataFrame(data, columns=['POS', 'Type', 'REF'])

    return reference_df

def read_vcf(path):
    """"
    Loads vcf file generated by lofreq
    """
    with open(path, 'r') as f:
        lines = [l for l in f if not l.startswith('##')]
    return pd.read_csv(
        io.StringIO(''.join(lines)),
        dtype={'#CHROM': str, 'POS': int, 'ID': str, 'REF': str, 'ALT': str,
               'QUAL': str, 'FILTER': str, 'INFO': str},
        sep='\t'
    ).rename(columns={'#CHROM': 'CHROM'})

def extract_af(info):
    """
    Extracts AF into a seperate column
    """
    match = re.search(r'AF=([\d\.]+)', info)

    return match.group(1) if match else None

def filter_df(df):
    """
    Extracts majority alleles from variant calling by filtering df for AF > 0.5 at each position
    """
    df['AF'] = df['INFO'].apply(extract_af)
    df['AF'] = df['AF'].astype(float)
    filtered_df = df[df['AF'] > 0.5] 

    return filtered_df

def merge_df(reference_df, filtered_df):
    """
    Merges reference allele with majority alleles
    """
    merged_df = reference_df.merge(filtered_df[['POS', 'ALT']], on='POS', how='left')
    merged_df['REF'] = merged_df.apply(lambda row: row['ALT'] if pd.notnull(row['ALT']) else row['REF'], axis=1)
    merged_df.drop('ALT', axis=1, inplace=True)

    return merged_df

def main():
    # original_reference_path = '/Users/fionachow/Documents/NYU/CDS/Summer 2024/Human rDNA Research/Project/Human-rDNA/original reference/rDNA_prototype_prerRNA_only.fa'
    # individual_path = '/Users/fionachow/Documents/NYU/CDS/Spring 2024/Research Fair/Hochwagen/Individual Data/ERR3240115/ERR3240115_rDNA.vcf'
    # check_indv = '/Users/fionachow/Documents/NYU/CDS/Spring 2024/Research Fair/Hochwagen/Individual Data/ERR3240115/reference_ERR3240115.csv' #the sample file generated from notebook for 1 individual
    # check_og = '/Users/fionachow/Documents/NYU/CDS/Spring 2024/Research Fair/Hochwagen/Individual Data/ERR3240115/ERR3240115_rDNA.mpileup' #the mpileup format

    individual_path = "xxx"
    # og_ref = fasta_to_all_chars_dataframe(original_reference_path)
    og_ref = "xxx"
    individual_df = read_vcf(individual_path)
    # check_df = pd.read_csv(check_indv)
    # check_og = pd.read_csv(check_og, sep='\t', header=None, usecols=[0, 1, 2], names=['CHROM', 'POS', 'REF'])
    
    filtered_df = filter_df(individual_df)
    merged_df = merge_df(og_ref, filtered_df)

    # assert check_df['POS'].equals(merged_df['POS']) and check_df['REF'].equals(merged_df['REF'])
    # assert check_og['POS'].equals(og_ref['POS']) and check_og['REF'].equals(og_ref['REF'])

    file_split = individual_path.split('/')
    id_value = file_split[-2]
    # os.chdir('/Users/fionachow/Documents/NYU/CDS/Summer 2024/Human rDNA Research/Project/Human-rDNA/outputs')
    os.chdir('xxx')
    # og_ref.to_csv('og_ref.csv', index=False)
    merged_df.to_csv(f'reference_{id_value}.csv', index=False)

    print(f'{id_value} reference saved.')
    
if __name__ == "__main__":
    main()
