import io
import os
import pandas as pd
import re

def fasta_to_all_chars_dataframe(filepath):
    """ 
    Parses a FASTA file and returns a DataFrame with all characters enumerated
    """
    with open(filepath, 'r') as file:
        position = 1  
        data = []  
        for line in file:
            for char in line:
                if char == '\n':
                    data.append((position, 'line_break', '\\n'))
                else:
                    data.append((position, 'sequence' if char != '>' else 'header', char))
                position += 1

    return pd.DataFrame(data, columns=['POS', 'Type', 'REF'])

def read_vcf(path):
    """"
    Loads vcf file generated by lofreq
    """
    with open(path, 'r') as f:
        lines = [l for l in f if not l.startswith('##')]
    return pd.read_csv(
        io.StringIO(''.join(lines)),
        dtype={'#CHROM': str, 'POS': int, 'ID': str, 'REF': str, 'ALT': str,
               'QUAL': str, 'FILTER': str, 'INFO': str},
        sep='\t'
    ).rename(columns={'#CHROM': 'CHROM'})

def extract_af(info):
    match = re.search(r'AF=([\d\.]+)', info)
    return match.group(1) if match else None

def filter_df(df):
    """
    Extracting majority alleles from variant calling by filtering df for AF > 0.5 at each position
    """
    df['AF'] = df['INFO'].apply(extract_af)
    df['AF'] = df['AF'].astype(float)
    filtered_df = df[df['AF'] > 0.5] 

    return filtered_df


def main():
  

if __name__ == "__main__":
    main()
