import io
import os
import pandas as pd
import re

def fasta_to_all_chars_dataframe(filepath):
    """ 
    Parses a FASTA file and returns a DataFrame with all characters enumerated
    """
    with open(filepath, 'r') as file:
        position = 1  
        data = []  
        for line in file:
            for char in line:
                if char == '\n':
                    data.append((position, 'line_break', '\\n'))
                else:
                    data.append((position, 'sequence' if char != '>' else 'header', char))
                position += 1

    reference_df = pd.DataFrame(data, columns=['POS', 'Type', 'REF'])

    return reference_df

def read_vcf(path):
    """"
    Loads vcf file generated by lofreq
    """
    with open(path, 'r') as f:
        lines = [l for l in f if not l.startswith('##')]
    return pd.read_csv(
        io.StringIO(''.join(lines)),
        dtype={'#CHROM': str, 'POS': int, 'ID': str, 'REF': str, 'ALT': str,
               'QUAL': str, 'FILTER': str, 'INFO': str},
        sep='\t'
    ).rename(columns={'#CHROM': 'CHROM'})

def extract_af(info):
    """
    Extracts AF into a seperate column
    """
    match = re.search(r'AF=([\d\.]+)', info)

    return match.group(1) if match else None

def filter_df(df):
    """
    Extracts majority alleles from variant calling by filtering df for AF > 0.5 at each position
    """
    df['AF'] = df['INFO'].apply(extract_af)
    df['AF'] = df['AF'].astype(float)
    filtered_df = df[df['AF'] > 0.5] 

    return filtered_df

def merge_df(reference_df, filtered_df):
    """
    Merges reference allele with majority alleles
    """
    merged_df = reference_df.merge(filtered_df[['POS', 'ALT']], on='POS', how='left')
    merged_df['REF'] = merged_df.apply(lambda row: row['ALT'] if pd.notnull(row['ALT']) else row['REF'], axis=1)
    merged_df.drop('ALT', axis=1, inplace=True)


def main():
    original_reference_path = ''
    individual_path = ''
    check_indv = '' #the sample file generated from notebook for 1 individual
    check_og = '' #the mpileup format

    og_ref = fasta_to_all_chars_dataframe(original_reference_path)
    individual_df = read_vcf(individual_path)
    check_df = pd.read_csv(check_indv)
    check_og = pd.read_csv(check_og, sep='\t', header=None, usecols=[0, 1, 2], names=['CHROM', 'POS', 'REF'])
    
    extract_df = extract_af(individual_df)
    filter_df = filter_df(extract_df)
    merge_df = merge_df(og_ref, filter_df)

    assert check_df['POS'].equals(merge_df['POS']) and check_df['REF'].equals(merge_df['REF'])
    assert check_og['POS'].equals(og_ref['POS']) and check_og['REF'].equals(og_ref['REF'])

    file_split = individual_path.split('_')
    id_value = file_split[0]
    og_ref.to_csv('og_ref.csv', index=False)
    merge_df.to_csv(f'reference_{id_value}.csv', index=False)

    print(f'{id_value} reference saved.')

if __name__ == "__main__":
    main()
